### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by BitesizedLion** [jdemaeyer/spoqify#2]
Hi, I'm trying to make an extension for [spicetify](https://spicetify.app/), however running into issues due to CORS:
https://github.com/jdemaeyer/spoqify/blob/b3bda2693a43b4e2cd00df0104aef2a99d113f08/spoqify/routes.py#L77

Example:
```
Access to fetch at 'https://open.spoqify.com/anonymize?url=4OP5WAgjpenZu9Z1sLoeu6' from origin 'https://xpui.app.spotify.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://spoqify.com' that is not equal to the supplied origin.
```

Do you think it'd be possible for you to change the CORS policy so I don't have to self-host?

**Comment by jdemaeyer** [comment]
Hi @BitesizedLion, that's amazing! I've always wondered how a better integration with Spotify's native client could be possible.

I've changed the CORS headers to allow requests from `spotify.com` and its subdomains -- let me know if it works!

**Comment by BitesizedLion** [comment]
> Hi @BitesizedLion, that's amazing! I've always wondered how a better integration with Spotify's native client could be possible.
> 
> I've changed the CORS headers to allow requests from `spotify.com` and its subdomains -- let me know if it works!

@jdemaeyer It does indeed work! I really do appreciate that you've made the change.


https://user-images.githubusercontent.com/42980888/235306947-1a2d8eef-bc77-42bb-8e78-3fcc248ee751.mp4

**Comment by jdemaeyer** [comment]
Looks awesome! I'm playing around with spicetify now and would love to try out your extension if you're okay with sharing the code?

**Comment by BitesizedLion** [comment]
> Looks awesome! I'm playing around with spicetify now and would love to try out your extension if you're okay with sharing the code?

@jdemaeyer Sure, I'm planning to publish it properly but here's a gist for now: https://gist.github.com/BitesizedLion/a45d776b50222bb8aec6a567301b9a2c

I've been using it the past few days and I'm pretty pleased

**Comment by jdemaeyer** [comment]
@BitesizedLion Thanks a lot for sharing! I think I could extend Spoqify to accept track IDs/URLs (e.g. https://open.spotify.com/track/4ZLzoOkj0MPWrTLvooIuaa), would that allow placing a "Go to Anonymous Song Radio" entry in song context menus so we could eliminate the extra step of having to open the (original, personalized) song radio first?

**Comment by BitesizedLion** [comment]
> @BitesizedLion Thanks a lot for sharing! I think I could extend Spoqify to accept track IDs/URLs (e.g. [open.spotify.com/track/4ZLzoOkj0MPWrTLvooIuaa](https://open.spotify.com/track/4ZLzoOkj0MPWrTLvooIuaa)), would that allow placing a "Go to Anonymous Song Radio" entry in song context menus so we could eliminate the extra step of having to open the (original, personalized) song radio first?

@jdemaeyer Yep, that would work.

I tried making a context menu for a track and getting the ID:
![image](https://user-images.githubusercontent.com/42980888/235998715-24c5a664-ff2e-43ef-b80b-0e6ba175d2e2.png)
![image](https://user-images.githubusercontent.com/42980888/235998776-027e3b15-28bf-4c92-b470-4dee5fb82012.png)

**Comment by jdemaeyer** [comment]
Sweet! I've added (actually, as I later realized, updated :sweat_smile:) support for track IDs. Both of these formats should work:

* https://open.spoqify.com/anonymize?url=track:4ZLzoOkj0MPWrTLvooIuaa
* https://open.spoqify.com/anonymize?url=https://open.spotify.com/track/4ZLzoOkj0MPWrTLvooIuaa

**Comment by BitesizedLion** [comment]
> Sweet! I've added (actually, as I later realized, updated sweat_smile) support for track IDs. Both of these formats should work:
> 
> * [open.spoqify.com/anonymize?url=track:4ZLzoOkj0MPWrTLvooIuaa](https://open.spoqify.com/anonymize?url=track:4ZLzoOkj0MPWrTLvooIuaa)
> * [open.spoqify.com/anonymize?url=https://open.spotify.com/track/4ZLzoOkj0MPWrTLvooIuaa](https://open.spoqify.com/anonymize?url=https://open.spotify.com/track/4ZLzoOkj0MPWrTLvooIuaa)

@jdemaeyer Alright! I gave it a shot and this does seem like the better approach.

New one: https://gist.github.com/BitesizedLion/3693e3aebf8caf2dd427e6b8c7ddec74


https://user-images.githubusercontent.com/42980888/236052626-0e38da5b-2876-4547-ae3b-bd151486fd02.mp4

**Comment by jdemaeyer** [comment]
omg this is so dope :heart_eyes: soooo much nicer I'm now using the local app instead of the web interface

If you do end up publishing it feel free to ping me and I'll happily add a link to the Spoqify homepage!

**Comment by BitesizedLion** [comment]
> If you do end up publishing it feel free to ping me and I'll happily add a link to the Spoqify homepage!

@jdemaeyer Wanted to let you know I have published it! :)

I'm very happy it's all working properly, and again really appreciate the changes you made 👍

https://github.com/BitesizedLion/AnonymizedRadios

**Comment by jdemaeyer** [comment]
Very cool, I've added a section to the landing page!
