### ISSUE TITLE
Unable to get playlists

### ISSUE THREAD

**Issue by moqca** [jdemaeyer/spoqify#3]
Hello! 
I'm unable to get a working URL.
Is there a specifit type of palylist this works on?
I've tried the following with out any of them working 

Artist Radio: https://open.spotify.com/playlist/37i9dQZF1E4mRu3Yn8v4Va
Mix: https://open.spotify.com/playlist/37i9dQZF1EQn4jwNIohw50

For all of them, getting the following result:
![image](https://user-images.githubusercontent.com/2406146/235764782-4a3c1b8e-4866-47e9-9b95-7f88f57c07e8.png)

**Comment by jdemaeyer** [comment]
I think these were related to an issue with our Spotify API auth token expiring prematurely that I fixed (?) via cf93253

Please re-open if the issue persists!
