### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by wadeosg** [jdemaeyer/spoqify#4]
While using spoqify's GUI, I repeatedly got an error for "400 Bad Request". This is the same for `open.spoqify.com/anonymize`
![image](https://github.com/jdemaeyer/spoqify/assets/126545818/07e7de5d-83aa-4ce3-880b-368d2ce08a25)
Response from `http://open.spoqify.com/anonymize?url=https://open.spotify.com/track/5ruzrDWcT0vuJIOMW7gMnW`:
```
event: error
data: 400, message='Bad Request', url=URL('https://api.spotify.com/v1/users/31mx2sz2lbgwpszoa6pcnugj4vcq/playlists')

```

**Comment by jdemaeyer** [comment]
Hi @wadeosg, thanks for the report!

Turns out that Spotify has an undocumented limit of 11,000 playlists per user. I've deleted (unfollowed) some old playlists and service should now be restored :)

**Comment by jdemaeyer** [comment]
https://github.com/jdemaeyer/spoqify/commit/ab1088abe83bdc3f1c612b601c6c5c67db42dee6

(also added a cronjob on the server to run this every hour)
