### ISSUE TITLE
Putting the original playlist url beats anonymization purpose

### ISSUE THREAD

**Issue by nijippoi** [jdemaeyer/spoqify#6]
@jdemaeyer
Hi! Thank you for a very useful tool.
The tool includes the original playlist url on the description of anonymized playlist, like so on the following lines.
https://github.com/jdemaeyer/spoqify/blob/4ac4186197fae0979444b57fed9aced859268bbf/spoqify/anonymization.py#L154-L155
Spotify playlist shows the author of the playlist so whenever another user opens the original playlist link on the anonymized playlist, we can see the original author, which beats the purpose of anonymization.
Would be great if there's a flag on the function, and a checkbox on the page to include/exclude the original playlist link, or just not putting the link itself.
Cheers!

**Comment by jdemaeyer** [comment]
Hi @nijippoi, thanks for reaching out!

Spoqify is not an anonymizer in the sense of "hide the author of a playlist from the world" — it is an anonymizer in the sense of "hide my listening history from Spotify". That is, an anonymizer in the sense of **show me the playlist with the same songs an anonymous user sees**, i.e. without all the personalization that Spotify adds to a playlist based on the user's listening history. "Un-personalizer" is maybe a more fitting term for Spoqify.

In fact, it should not even be possible to run Spoqify on user-generated playlists - only Spotify-generated playlists (like Song Radio) should work. If you somehow did that, you've found a bug ;) Could you post a link to the playlist you wanted to anonymize (in your original sense) and were then confused over the link to the original playlist?
